version: 2.1

defaults: &defaults
  docker:
    - image: cypress/base:12
  working_directory: ~/cypress-axe

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Checking Versions
          command: |
              node --version
              npm --version
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - '*'

  publish:
    <<: *defaults
    environment:
      JFROG_NPM_URL: https://udacity.jfrog.io/artifactory/api/npm/npm
    steps:
      - attach_workspace:
          at: ~/cypress-axe
      - run:
          name: Set npm registry to jfrog
          command: npm config set @udacity:registry $JFROG_NPM_URL
      - run:
          name: Login to npm repository
          command: curl -s -o .npmrc -u "$JFROG_CLI_USER:$JFROG_CLI_APIKEY" $JFROG_NPM_URL/auth/udacity
      - run:
          name: Publish to registry
          command: npm publish

workflows:
  version: 2
  build-publish:
    jobs:
      - build:
          context: org-global
          # tags may be of the form v1.2.3.pre.1
          filters:
            tags:
              only: /^v?\d+\.\d+\.\d+.*/
      - publish:
          requires:
            - build
          context: org-global
          # include release tags of the form v1.2.3, v1.2.3.pre.1
          filters:
            tags:
              only: /^v?\d+\.\d+\.\d+.*/
            branches:
              ignore: /.*/
